targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - strict_raw_type
            - document_ignores
            - cast_nullable_to_non_nullable
            - unnecessary_null_checks
            - specify_nonobvious_property_types
          preamble: |
            // dart format off
      json_serializable:
        options:
          any_map: true
          checked: true
          constructor: ""
          create_factory: true
          create_field_map: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: false
