#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

dart format --set-exit-if-changed $(find lib test -name '*.dart' -not -name '*.g.dart')
dart analyze --fatal-infos --fatal-warnings lib test
dart test