name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Set Google service-account
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: echo "GOOGLE_SERVICE_ACCOUNT_KEY="$(echo $SERVICE_ACCOUNT | base64 --decode)"" >> $GITHUB_ENV

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git
            semantic-release-pub
            @semantic-release/changelog
